exclude: (LICENSE|README.md|setup.py|notebooks/)
repos:
  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        language_version: python3

  # # isort - Sorting imports
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort
  #       args: ["--filter-files"]

  # yapf - is doing my head in with making modifications, so removing as it make non-pep8
  # compliant changes
  #- repo: https://github.com/google/yapf
  #  rev: v0.40.2
  #  hooks:
  #    - id: yapf
  #      name: "yapf"
  #      args: ["--in-place", "--parallel"]
  #      exclude: "docs/"

  # ruff - Linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: []

  - repo: local
    hooks:
      # Run pytest
      - id: pytest
        name: Run pytest
        entry: pytest
        language: system
        pass_filenames: false
